; includes
(import "pkg::disp-text@://vesc_packages/lib_disp_ui/disp_ui.vescpkg" 'disp-text)
(import "pkg::disp-text@://vesc_packages/lib_disp_ui/disp_ui.vescpkg" 'disp-text)
(import "res/BKB_LOGO.jpg" 'logo)

(import "res/soc_box.lisp" 'soc_box)
(import "fonts/font_9x14.bin" font_9x14)
(import "fonts/font_11x14_b.bin" font_11x14_b)
(import "fonts/font_20x30.bin" font_20x30)
(import "fonts/font_13x16_b.bin" font_13x16_b)
(import "res/speed_box.lisp" 'speed_box)
(import "res/dir_box.lisp" 'dir_box)
(import "res/conn_box.lisp" 'conn_box)
(import "res/mode_box.lisp" 'mode_box)
(import "res/amps_box.lisp" 'amps_box)
(import "res/trip_box.lisp" 'trip_box)
(import "screens/calib_screen.lisp" 'calib_screen)
(import "res/clear.lisp" 'clear)
(import "res/on_off_secuence.lisp" 'on_off_secuence)
(import "res/read_inputs.lisp" 'read_inputs)
(import "screens/info_screen.lisp" 'info_screen)

(read-eval-program disp-text)
(read-eval-program speed_box)
(read-eval-program soc_box)
(read-eval-program dir_box)
(read-eval-program conn_box)
(read-eval-program mode_box)
(read-eval-program amps_box)
(read-eval-program trip_box)
(read-eval-program calib_screen)
(read-eval-program clear)
(read-eval-program on_off_secuence)
(read-eval-program read_inputs)


(define x_offset 2)
(define y_offset 67)
(disp-load-st7735 6 5 8 7 9 30) ; for some reason the first attempt to init is not succesful
(disp-load-st7735 6 5 8 7 9 30)
(disp-reset)
(clear_screen)
(ext-disp-orientation 2)

(gpio-write 20 1) 
(disp-render-jpg logo (+ x_offset 0) (+ y_offset 12))
(sleep 2)
;(on_secuence)
(clear_screen)
(write_mode 0 (+ x_offset 2) (+ y_offset 20))
(write_online 0 (+ x_offset 95) (+ y_offset 19))
(write_direction 0  (+ x_offset 59) (+ y_offset 0))
(def count 100)
(bat_soc count 0 100 1 1  (+ x_offset 85) (+ y_offset 0))
(bat_soc count 36 48 0 0  (+ x_offset 8) (+ y_offset 0))
(write_amps 100.2 (+ x_offset 3) (+ y_offset 50))
(write_trip 150.4 0 (+ x_offset 60) (+ y_offset 50))

(sleep 1)
(write-speed 41.5 0 (+ x_offset 33) (+ y_offset 19) 1)
(sleep 1)
(write-speed 41.5 0 (+ x_offset 33) (+ y_offset 19) 2)
(sleep 1)
(write-speed 41.5 0 (+ x_offset 33) (+ y_offset 19) 3)


(sleep 1)
(write_online 1 (+ x_offset 95) (+ y_offset 18))
(sleep 1)
(write_direction 0 (+ x_offset 59) (+ y_offset 0))
(sleep 1)
(write_direction 1 (+ x_offset 59) (+ y_offset 0))
(sleep 1)
(write_mode 0 (+ x_offset 2) (+ y_offset 20))
(sleep 1)
(write_mode 1 (+ x_offset 2) (+ y_offset 20))
(sleep 1)
(write_mode 2 (+ x_offset 2) (+ y_offset 20))
(sleep 1)
(write_mode 3 (+ x_offset 2) (+ y_offset 20))
(sleep 1)
(write_trip 150.4 1 (+ x_offset 60) (+ y_offset 50))

(loopwhile (> count 0) {
        (bat_soc count 0 100 1 1 (+ x_offset 85) (+ y_offset 0))
        (bat_soc count 36 48 0 0 (+ x_offset 8) (+ y_offset 0))
        (sleep 0.3)
        (setvar 'count (- count 1))
        (print count)
})


;(clear_screen)
;(calib_screen)


